name: Run UI E2E test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  selenium-tests:
    runs-on: ubuntu-latest


    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb


    #    services:
#      selenium-hub:
#        image: selenium/hub:4.28.0
#        ports:
#          - 4444:4444
#        options: --network-alias=selenium-hub
#      chrome:
#        image: selenium/node-chrome:4.28.0
#        options: >
#          --network-alias=chrome
#          --env SE_EVENT_BUS_HOST=selenium-hub
#          --env SE_EVENT_BUS_PUBLISH_PORT=4442
#          --env SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      firefox:
#        image: selenium/node-firefox:4.28.0
#        options: >
#          --network-alias=firefox
#          --env SE_EVENT_BUS_HOST=selenium-hub
#          --env SE_EVENT_BUS_PUBLISH_PORT=4442
#          --env SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn install -DskipTests

      - run: curl http://localhost:4444/status

      - name: Run Selenium Tests
        run: mvn test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ./allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
