name: Run UI E2E test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        default: 'test'
        required: true
        options:
          - test
          - tba
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'test'
        required: false
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.28.0
        ports:
          - 4444:4444
        options: >
          --network-alias=selenium-hub
          --env SE_SESSION_REQUEST_TIMEOUT=30000
          --env SE_NODE_SESSION_TIMEOUT=30000
      chrome:
        image: selenium/node-chrome:4.28.0
        options: >
          --network-alias=chrome
          --env SE_EVENT_BUS_HOST=selenium-hub
          --env SE_EVENT_BUS_PUBLISH_PORT=4442
          --env SE_EVENT_BUS_SUBSCRIBE_PORT=4443
          --env SE_NODE_MAX_SESSIONS=1

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Wait for Selenium Hub to be ready
        run: |
          timeout=60
          while [ $timeout -gt 0 ]; do
            status=$(curl -s http://localhost:4444/status | jq -r '.value.ready')
            if [ "$status" = "true" ]; then
              echo "Selenium Hub is ready!"
              break
            fi
            echo "Waiting for Selenium Hub to be ready..."
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Selenium Hub did not become ready in time."
            exit 1
          fi

      - name: Run Selenium Tests
        run: |
          environment_lowercase=$(echo "${{inputs.environment}}" | tr '[:upper:]' '[:lower:]')
          echo "Running tests in the ${environment_lowercase} environment"
          mvn clean test -Denvironment=${environment_lowercase}

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ./allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
